services:
  - type: web
    name: iv-monitoring-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY
        value: IVMONITOR123
      - key: DROP_FACTOR
        value: 20
      - key: AUTO_DEMO
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: iv-monitoring-postgres
          property: connectionString

databases:
  - name: iv-monitoring-postgres
    plan: free
